# /addons/vcan_cannelloni/config.yaml
name: "VCAN Cannelloni Bridge"
version: "1.0.9" # Increment version
slug: "vcan_cannelloni"
description: "Sets up a vcan0 interface and runs cannelloni (bundled) to bridge CAN traffic." # Updated description
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
# Grant access to the Home Assistant API (needed for bashio::config)
homeassistant_api: true
# Privileged mode is required for 'ip link' commands
privileged:
  - NET_ADMIN
# Host network might be needed depending on how can0 is exposed
host_network: true
# REMOVED map: [share:ro] as binary is now copied into the image
schema:
  remote_ip: str
  local_can_interface: str

